# GLOBAL STUFF
model_version: 3.6B
dtype: bfloat16

# ControlNet specific
controlnet_blocks: [0, 4, 8, 12, 51, 55, 59, 63]
controlnet_filter: SRFilter
controlnet_filter_params: 
  scale_factor: 0.25

effnet_checkpoint_path: ../models/effnet_encoder.safetensors
previewer_checkpoint_path: ../models/previewer.safetensors
generator_checkpoint_path: ../models/stage_c_bf16.safetensors
controlnet_checkpoint_path: /weka/home-warp/models/v3_release/stage_c_3b_controlnet_sr/controlnet_10k.safetensors
