# GLOBAL STUFF
model_version: 3.6B
dtype: bfloat16

# ControlNet specific
controlnet_blocks: [0, 4, 8, 12, 51, 55, 59, 63]
controlnet_filter: CannyFilter
controlnet_filter_params: 
  resize: 224

effnet_checkpoint_path: models/effnet_encoder.safetensors
previewer_checkpoint_path: models/previewer.safetensors
generator_checkpoint_path: models/stage_c_bf16.safetensors
controlnet_checkpoint_path: models/canny.safetensors
