# GLOBAL STUFF
model_version: 3B

effnet_checkpoint_path: /weka/home-warp/models/release_checkpoints/effnet_encoder.safetensors
stage_a_checkpoint_path: /weka/home-warp/models/release_checkpoints/stage_a.safetensors
generator_checkpoint_path: /weka/home-warp/models/release_checkpoints/stage_b_bf16.safetensors
