# GLOBAL STUFF
experiment_id: stage_c_3b_controlnet_inpainting
checkpoint_path: /path/to/checkpoint
output_path: /path/to/output
model_version: 3.6B

# WandB
wandb_project: StableCascade
wandb_entity: wandb_username

# TRAINING PARAMS
lr: 1.0e-4
batch_size: 256
image_size: 768
# multi_aspect_ratio: [1/1, 1/2, 1/3, 2/3, 3/4, 1/5, 2/5, 3/5, 4/5, 1/6, 5/6, 9/16]
grad_accum_steps: 1
updates: 10000
backup_every: 2000
save_every: 1000
warmup_updates: 1
use_fsdp: True

# ControlNet specific
controlnet_blocks: [0, 4, 8, 12, 51, 55, 59, 63]
controlnet_filter: InpaintFilter
controlnet_filter_params: 
  thresold: [0.04, 0.4]
  p_outpaint: 0.4
offset_noise: 0.1

# CUSTOM CAPTIONS GETTER & FILTERS
captions_getter: ['txt', identity]
dataset_filters: 
  - ['width', 'lambda w: w >= 768']
  - ['height', 'lambda h: h >= 768']

# ema_start_iters: 5000
# ema_iters: 100
# ema_beta: 0.9

webdataset_path:
  - s3://path/to/your/first/dataset/on/s3
  - s3://path/to/your/second/dataset/on/s3
effnet_checkpoint_path: models/effnet_encoder.safetensors
previewer_checkpoint_path: models/previewer.safetensors
generator_checkpoint_path: models/stage_c_bf16.safetensors